# Generated by Django 4.2 on 2023-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
