# Generated by Django 4.2 on 2023-06-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_page_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='Untitled', max_length=64),
        ),
        migrations.AlterField(
            model_name='page',
            name='photo',
            field=models.CharField(blank=True, default='📄', max_length=100, null=True),
        ),
    ]
