# Generated by Django 4.2 on 2023-06-28 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_page_created_at_page_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_element',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='page_element',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
