# Generated by Django 4.2 on 2023-06-30 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_page_element_created_at_page_element_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='creator',
        ),
        migrations.AddField(
            model_name='page',
            name='creator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
