# Generated by Django 4.2 on 2023-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_page_creator_page_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
