# Generated by Django 4.2 on 2023-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_to_do_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='full_width',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
