# Generated by Django 4.2 on 2023-08-30 19:21

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_page_name_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', validators=[base.models.validate_file_size])),
                ('page_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='base.page_element')),
            ],
        ),
    ]
